(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var m=this||self;function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}} 
function n(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?n=aa:n=ba;return n.apply(null,arguments)};function p(a){p[" "](a);return a}p[" "]=function(){};var ca={},q=null;var da="function"===typeof Uint8Array;const u=Symbol(void 0);function v(a){Object.isFrozen(a)||(u?a[u]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};function ea(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var ka=Object.freeze(v([]));function A(a,b){return-1===b?null:b>=a.l?a.j?a.j[b]:void 0:a.g[b+a.i]}function D(a,b,c){a=A(a,b);return null==a?c:a}function E(a,b){a=A(a,b);a=null==a?a:!!a;return null==a?!1:a}function la(a){a=A(a,13);a=null==a?a:+a;return null==a?0:a};function ma(a,b=na){return oa(a,b)}function pa(a,b){if(null!=a){if(Array.isArray(a))a=oa(a,b);else if(ea(a)){const c={};for(let d in a)c[d]=pa(a[d],b);a=c}else a=b(a);return a}}function oa(a,b){const c=a.slice();for(let d=0;d<c.length;d++)c[d]=pa(c[d],b);if(b=Array.isArray(a)){let d;u?d=a[u]:d=a.g;b=(null==d?0:d)&1}b&&v(c);return c} 
function qa(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(a&&!Array.isArray(a)&&da&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!q){q={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));ca[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===q[h]&&(q[h]=g)}}}b=ca[b];c=Array(Math.floor(a.length/ 
3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var l=a[f],k=a[f+1];h=a[f+2];g=b[l>>2];l=b[(l&3)<<4|k>>4];k=b[(k&15)<<2|h>>6];h=b[h&63];c[e++]=g+l+k+h}g=0;h=d;switch(a.length-f){case 2:g=a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+h+d}a=c.join("")}}return Array.isArray(a)?ma(a,qa):a}function na(a){return da&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};let F;function ra(a){var b=sa;F=a=a?JSON.parse(a):null;b=new b(a);F=null;return b} 
var ta=class{constructor(a,b,c){var d=F;F=null;a||(a=d);d=this.constructor.messageId;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.g||0);this.g=a;a:{d=this.g.length;a=d-1;if(d&&(d=this.g[a],ea(d))){this.l=a-this.i;this.j=d;break a}void 0!==b&&-1<b?(this.l=Math.max(b,a+1-this.i),this.j=void 0):this.l=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.l)a+=this.i,(d=this.g[a])?Array.isArray(d)&&v(d):this.g[a]=ka;else{d=this.j||(this.j=this.g[this.l+this.i]={});let e=d[a];e?Array.isArray(e)&& 
v(e):d[a]=ka}}toJSON(){return ma(this.g,qa)}};ta.prototype.toString=function(){return this.g.toString()};var ua=class extends ta{};const va=()=>{Object.defineProperties(ua,{[Symbol.hasInstance]:{value:Object[Symbol.hasInstance],configurable:!1,writable:!1,enumerable:!1}})};va();class wa extends ua{}const xa=()=>{Object.defineProperties(wa,{[Symbol.hasInstance]:{value:Object[Symbol.hasInstance],configurable:!1,writable:!1,enumerable:!1}})};xa();var sa=class extends wa{constructor(a){super(a)}};function G(a,b){if(!b(a))throw Error(String(a));return a};var ya=a=>"string"===typeof a,H=a=>!!a&&("object"===typeof a||"function"===typeof a);function za(a,b){var c=G(JSON.parse(a.name),H);c=G(c._context,H);const d=G(c.mode,H);c={version:G(d.rtvVersion,ya),W:G(c.sentinel,ya)};const {version:e,W:f}=c;b.sentinel=f;a.parent.postMessage(`amp-${e}${JSON.stringify(b)}`,"*")};function Aa(a=window){return a};var I=window;/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function J(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)}function K(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};var Ba=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ca(a,b){if(a)for(const c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}let L=[];const M=()=>{const a=L;L=[];for(const b of a)try{b()}catch(c){}};var Da=(a,b)=>{"complete"===a.readyState||"interactive"===a.readyState?(L.push(b),1==L.length&&(window.Promise?Promise.resolve().then(M):window.setImmediate?setImmediate(M):setTimeout(M,0))):a.addEventListener("DOMContentLoaded",b)};function Ea(a=document){return a.createElement("img")};function Fa(a,b,c=null){Ga(a,b,c)}function Ga(a,b,c){a.google_image_requests||(a.google_image_requests=[]);const d=Ea(a.document);if(c){const e=f=>{c&&c(f);K(d,"load",e);K(d,"error",e)};J(d,"load",e);J(d,"error",e)}d.src=b;a.google_image_requests.push(d)};let Ha=0;function Ia(a){return(a=Ja(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function Ja(a,b=null){return b&&b.getAttribute("data-jc")===String(a)?b:document.querySelector(`[${"data-jc"}="${a}"]`)};class Oa{constructor(a,b){this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta={}}};const Pa=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");var Qa=class{constructor(a,b){this.g=a;this.i=b}},Ra=class{constructor(a,b){this.url=a;this.V=!!b;this.depth=null}};function O(a,b){const c={};c[a]=b;return[c]}function Sa(a,b,c,d,e){const f=[];Ca(a,function(g,h){(g=Ta(g,b,c,d,e))&&f.push(h+"="+g)});return f.join(b)} 
function Ta(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){const f=[];for(let g=0;g<a.length;g++)f.push(Ta(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Sa(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}function Ua(a){let b=1;for(const c in a.i)b=c.length>b?c.length:b;return 3997-b-a.j.length-1} 
function Va(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;let d=Ua(a)-c.length;if(0>d)return"";a.g.sort(function(f,g){return f-g});c=null;let e="";for(let f=0;f<a.g.length;f++){const g=a.g[f],h=a.i[g];for(let l=0;l<h.length;l++){if(!d){c=null==c?g:c;break}let k=Sa(h[l],a.j,",$");if(k){k=e+k;if(d>=k.length){d-=k.length;b+=k;e=a.j;break}c=null==c?g:c}}}a="";null!=c&&(a=e+"trn="+c);return b+a}class Wa{constructor(){this.j="&";this.i={};this.l=0;this.g=[]}};function Xa(){var a=P,b=Q.google_srt;0<=b&&1>=b&&(a.g=b)}function Ya(a,b,c,d,e,f){if((d?a.g:Math.random())<(e||.01))try{let g;c instanceof Wa?g=c:(g=new Wa,Ca(c,(l,k)=>{var w=g,r=w.l++;l=O(k,l);w.g.push(r);w.i[r]=l}));const h=Va(g,a.i,"/pagead/gen_204?id="+b+"&");h&&("undefined"!==typeof f?Fa(m,h,f):Fa(m,h))}catch(g){}}class Za{constructor(){this.i="http:"===I.location.protocol?"http:":"https:";this.g=Math.random()}};let R=null;var $a=()=>{const a=m.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},ab=()=>{const a=m.performance;return a&&a.now?a.now():null};class bb{constructor(a,b){var c=ab()||$a();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const S=m.performance,cb=!!(S&&S.mark&&S.measure&&S.clearMarks),T=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=cb){var b;if(null===R){R="";try{a="";try{a=m.top.location.hash}catch(c){a=m.location.hash}a&&(R=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=R;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function db(a){a&&S&&T()&&(S.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),S.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class eb{constructor(){var a=Q;this.events=[];this.i=a||m;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.events=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=T()||(null!=b?b:1>Math.random())}start(a,b){if(!this.g)return null;a=new bb(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;S&&T()&&S.mark(b);return a}end(a){if(this.g&&"number"===typeof a.value){a.duration=(ab()||$a())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;S&&T()&&S.mark(b);!this.g|| 
2048<this.events.length||this.events.push(a)}}};function fb(a){let b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);let c;for(;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(c){}}return b} 
function gb(a,b,c){let d,e;try{a.g&&a.g.g?(e=a.g.start(b.toString(),3),d=c(),a.g.end(e)):d=c()}catch(f){c=!0;try{db(e),c=a.m(b,new Oa(f,{message:fb(f)}),void 0,void 0)}catch(g){a.J(217,g)}if(c){let g,h;null==(g=window.console)||null==(h=g.error)||h.call(g,f)}else throw f;}return d}function hb(a,b){var c=U;return(...d)=>gb(c,a,()=>b.apply(void 0,d))} 
class ib{constructor(a=null){this.j=P;this.i=null;this.m=this.J;this.g=a;this.l=!1}pinger(){return this.j}J(a,b,c,d,e){e=e||"jserror";let f;try{const x=new Wa;var g=x;g.g.push(1);g.i[1]=O("context",a);b.error&&b.meta&&b.id||(b=new Oa(b,{message:fb(b)}));if(b.msg){g=x;var h=b.msg.substring(0,512);g.g.push(2);g.i[2]=O("msg",h)}var l=b.meta||{};b=l;if(this.i)try{this.i(b)}catch(t){}if(d)try{d(b)}catch(t){}d=x;l=[l];d.g.push(3);d.i[3]=l;d=m;l=[];let V;b=null;do{var k=d;try{var w;if(w=!!k&&null!=k.location.href)b:{try{p(k.foo); 
w=!0;break b}catch(t){}w=!1}var r=w}catch(t){r=!1}r?(V=k.location.href,b=k.document&&k.document.referrer||null):(V=b,b=null);l.push(new Ra(V||""));try{d=k.parent}catch(t){d=null}}while(d&&k!=d);for(let t=0,Ka=l.length-1;t<=Ka;++t)l[t].depth=Ka-t;k=m;if(k.location&&k.location.ancestorOrigins&&k.location.ancestorOrigins.length==l.length-1)for(r=1;r<l.length;++r){var B=l[r];B.url||(B.url=k.location.ancestorOrigins[r-1]||"",B.V=!0)}var y=l;let fa=new Ra(m.location.href,!1);k=null;const ha=y.length-1; 
for(B=ha;0<=B;--B){var z=y[B];!k&&Pa.test(z.url)&&(k=z);if(z.url&&!z.V){fa=z;break}}z=null;const xb=y.length&&y[ha].url;0!=fa.depth&&xb&&(z=y[ha]);f=new Qa(fa,z);if(f.i){y=x;var C=f.i.url||"";y.g.push(4);y.i[4]=O("top",C)}var ia={url:f.g.url||""};if(f.g.url){var ja=f.g.url.match(Ba),N=ja[1],La=ja[3],Ma=ja[4];C="";N&&(C+=N+":");La&&(C+="//",C+=La,Ma&&(C+=":"+Ma));var Na=C}else Na="";N=x;ia=[ia,{url:Na}];N.g.push(5);N.i[5]=ia;Ya(this.j,e,x,this.l,c)}catch(x){try{Ya(this.j,e,{context:"ecmserr",rctx:a, 
msg:fb(x),url:f&&f.g.url},this.l,c)}catch(V){}}return!0}};class jb{};let P,U;const Q=window,W=new eb;var kb=()=>{Q.google_measure_js_timing||(W.g=!1,W.events!=W.i.google_js_reporting_queue&&(T()&&Array.prototype.forEach.call(W.events,db,void 0),W.events.length=0))};(a=>{P=null!=a?a:new Za;"number"!==typeof Q.google_srt&&(Q.google_srt=Math.random());Xa();U=new ib(W);U.i=b=>{const c=Ha;0!==c&&(b.jc=String(c),b.shv=Ia(c))};U.l=!0;"complete"==Q.document.readyState?kb():W.g&&J(Q,"load",()=>{kb()})})(); 
var X=(a,b)=>hb(a,b),lb=(a,b,c)=>{var d=jb,e="U";d.U&&d.hasOwnProperty(e)||(e=new d,d.U=e);d=[];!b.eid&&d.length&&(b.eid=d.toString());Ya(P,a,b,!0,c,void 0)};function Y(a,b,c={}){c.msg_type=b;c.googMsgType="sth";b=JSON.stringify(c);a.parent.postMessage(b,"*")}function mb(a){if(a.C||E(a.i,2))return!0;let b=!0;const c=nb(a);c&&(b=36E5<=c);if(b)try{a.g.localStorage.removeItem("LAST_INTERSTITIAL_TIME")}catch(d){}return b}function Z(a,b,c){D(a.i,3,"")&&(b.qid=D(a.i,3,""));D(a.i,10,"")&&(b.eid=D(a.i,10,""));b.rtype=D(a.i,12,0);b.req=I.location.href;lb(a.M(),b,c)} 
function nb(a){try{const b=+a.g.localStorage.getItem("LAST_INTERSTITIAL_TIME"),c=Date.now();if(b&&b<c)return c-b}catch(b){}return null} 
class ob{constructor(a,b){this.g=I;this.m=a;this.s=!1;this.A=null;this.l=0;this.i=b;this.C=E(this.i,11)||10===D(this.i,12,0)||11===D(this.i,12,0)}M(){}F(){if(this.s=mb(this))this.G(),D(this.i,1,"")&&this.g.parent.postMessage(D(this.i,1,""),"*")}v(){if(!this.l){this.A&&K(this.g,"storage",this.A);this.l=Date.now();if(!E(this.i,2)&&!this.C)try{this.g.localStorage.setItem("LAST_INTERSTITIAL_TIME",""+this.l)}catch(b){}this.T();if(this.m){var a=this.g.document.createEvent("Event");a.initEvent("i-creative-view", 
!0,!1);this.m.dispatchEvent(a);a=this.g.document.createEvent("Event");a.initEvent("onshow",!0,!1);this.g.dispatchEvent(a)}}}N(){}G(){let a=!1;this.g.IntersectionObserver&&.01<la(this.i)&&(a=!0,(new this.g.IntersectionObserver((b,c)=>{b.forEach(d=>{if(!(0>=d.intersectionRatio)){this.v();for(const e of this.m.document.getElementsByClassName("GoogleActiveViewElement"))e.removeAttribute("data-google-av-dm");c.disconnect()}})},{threshold:la(this.i)})).observe(this.g.document.documentElement));J(this.g, 
"message",X(262,b=>{a:{var c=a;if(b&&(this.g.parent==b.source||this.g.parent.parent==b.source)){var d={};try{d=this.g.JSON.parse(b.data)}catch(f){b=void 0;break a}var e;switch(null==(e=d)?void 0:e.msg_type){case "i-view":this.s&&!c&&this.v();Z(this,{type:"viewmsg",has_iobs:!!this.g.IntersectionObserver});break;case "r-back-button":this.N()}}b=void 0}return b}));this.C||(this.A=X(263,()=>{this.s=mb(this);if(!this.s){var b={i_tslv:nb(this)};Y(this.g,"i-no",b)}}),J(this.g,"storage",this.A));E(this.i, 
22)?za(this.g,{type:"render-start",interstitialCloseBtn:!0,width:-1,height:-1}):Y(this.g,"i-adframe-load")}T(a){let b;try{const c=Aa(this.m);c.vv?c.vv():b=!0}catch(c){U.J(533,c,void 0,void 0);return}a=a||1;b?(Z(this,{vf:a}),3<=a||this.g.setTimeout(n(ob.prototype.T,this,a+1),3E3)):1<a&&Z(this,{vs:a})}};class pb{constructor(){this.promise=new Promise(a=>{this.resolve=a})}};function qb(a){window.parent.postMessage(JSON.stringify({type:"rewarded",message:a}),"*")};var rb=a=>{a=a.document;let b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}};function sb(a,b,c){lb("jserror",{context:"iaf::itf",req:I.location.href,db:a?1:0,ls:b?1:0,eid:D(c,10,""),qid:D(c,3,""),rtype:D(c,12,0)})}function tb(a,b){ub(a,b)&&(a.j.style.background="rgba(192,192,192, .3)",m.setTimeout(()=>{a.j.style.background="transparent";a.dismiss(2)},750))}function vb(a,b){b.some(c=>{let d;return"intervention"===c.type&&"HeavyAdIntervention"===(null==(d=c.body)?void 0:d.id)})&&(Z(a,{hai:"1"},1),a.l?a.dismiss(8):Y(a.g,"i_iif"))} 
function wb(a){const b=X(259,n(function(){Y(this.g,"i-blur");K(this.g,"blur",b)},a));J(a.g,"blur",b)}function yb(a){a.o||0===a.l||(a.j.setAttribute("aria-label",D(a.i,7,"")),a.j.setAttribute("role","button"),a.j.setAttribute("tabindex","0"),a.j.focus())}function zb(a,b){E(a.i,15)?(qb("canceled"),qb("closed")):E(a.i,22)?za(a.g,{type:"interstitial-close-ad",interstitialCloseBtn:!0}):Y(a.g,b)} 
function Ab(a,b){const c=a.g.document.getElementById("creative");a.g.goog_vignette_survey&&(a.g.goog_vignette_survey.display(c,()=>{a.dismiss(3)},()=>{},1),b&&b.stopPropagation())}function Bb(a){!1===a.o&&a.enableDismissListeners();a.R&&J(a.R,"click",X(261,c=>Ab(a,c)));const b=a.g.document.getElementById("card");b&&b.addEventListener("click",X(909,c=>{null==c||c.stopPropagation()}))} 
function Cb(a){J(a.g,"resize",()=>{var b=a.g;b=b.innerHeight>=b.innerWidth?1:2;a.D?(a.D=!1,a.I=2===b):(a.I?1===b:2===b)&&a.dismiss(4)})}function Db(a){a.g.addEventListener("message",b=>{if(b.source===a.m)try{const c=JSON.parse(b.data);"rewarded"===c.type&&"closed"===c.message&&a.dismiss(11===D(a.i,12,0)?6:1)}catch(c){}})} 
function ub(a,b){if(!b)return!0;if((b.preventDefault?b.defaultPrevented:!1===b.returnValue)||b.target&&b.target.ownerDocument==a.m.document)return!1;for(a=b.target;a;){if("creative"==a.id)return!1;a=a.parentElement}return!0} 
class Eb extends ob{constructor(a,b,c,d){super(a,d);this.j=b;this.R=c;this.K=0;this.P=X(260,e=>{this.dismiss(1);e&&e.stopPropagation()});this.O=e=>tb(this,e);this.H=[];this.B=[];this.o=!1;this.L=()=>{};this.D=this.I=!1;this.u=null}F(){super.F();(this.u=this.g.ReportingObserver?new this.g.ReportingObserver((a,b)=>{vb(this,a)&&b.disconnect()},{buffered:!0}):null)&&J(this.g,"unload",()=>{vb(this,this.u.takeRecords());this.u.disconnect()})}M(){return"ia_evt"}N(){this.o?this.L():this.dismiss(9)}addViewListener(a){a= 
hb(483,a);this.l?a():this.H.push(a)}addDismissListener(a){this.B.push(hb(484,a))}disableDismissListeners(a){this.o=!0;this.L=a;K(this.j,"click",this.P);K(this.g.document,"click",this.O)}enableDismissListeners(){this.o=!1;J(this.j,"click",this.P);J(this.g.document,"click",this.O);yb(this)}dismiss(a){document.body.setAttribute("aria-hidden","true");Z(this,{ttd:Date.now()-this.l,req:I.location.href,pda:this.K,ds:a,idrw:E(this.i,15)?1:0});this.K++||wb(this);let b=0;for(let d=0;d<this.B.length;d++)b=Math.max(b, 
this.B[d]());b=Math.min(b,1E3);let c="i-dismiss";6===a?c="r-dismiss-before-reward":7===a&&(c="r-dismiss-after-reward");0===b?zb(this,c):m.setTimeout(()=>zb(this,c),b)}G(){super.G();Bb(this)}v(){super.v();var a=this.g;this.I=2===(a.innerHeight>=a.innerWidth?1:2);this.D=0===this.g.innerWidth&&0===this.g.innerHeight;Cb(this);yb(this);var b=this.j.getBoundingClientRect(),c=b.bottom,d=b.right;a=rb(this.g).clientHeight;var e=rb(this.g).clientWidth,f=Math.floor(c-a);const g=Math.floor(d-e);if(0<=f||5<g)c-= 
b.top,d-=b.left,b=this.g,Z(this,{dhb:f>=c?1:0,dhr:g>=d?1:0,h:a,w:e,bh:c,bw:d,opb:f,opr:g,pt:b.innerHeight>=b.innerWidth?1:0,req:this.g.location.href});document.getElementById("ad_iframe").contentWindow.postMessage(JSON.stringify({type:"rewarded",message:"visible"}),"*");for(a=0;a<this.H.length;a++)this.H[a]();Db(this);if(!(.01<Math.random())){a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${24}&version=${Ia(24)}&sample=${.01}`;e=window;if(f=e.navigator)f=e.navigator.userAgent, 
f=/Chrome/.test(f)&&!/Edge/.test(f)?!0:!1;f&&e.navigator.sendBeacon?e.navigator.sendBeacon(a):Fa(e,a)}a=this.g.navigator?!0===this.g.navigator.standalone:!1;e=window.matchMedia("(display-mode: standalone)").matches;Z(this,{wapp:a||e})}};Ha=24;const Fb=Ja(24,document.currentScript);if(null==Fb)throw Error("JSC not found 24");const Gb={},Hb=Fb.attributes;for(let a=Hb.length-1;0<=a;a--){const b=Hb[a].name;0===b.indexOf("data-jcp-")&&(Gb[b.substring(9)]=Hb[a].value)} 
(function(a){const b=ra(a.config);a=X(258,()=>{{var c=document.getElementById("ad_iframe").contentWindow;var d=I.document;const g=c.document,h=D(b,5,0);var e=0===h||2===h?g.getElementById(D(b,6,"")):d.getElementById(D(b,6,""));d=0===h?g.getElementById(D(b,8,"")):d.getElementById(D(b,8,""));try{var f=!!I.localStorage}catch(l){}e?(f||sb(e,f,b),c=new Eb(c,e,d,b),c.F()):(sb(e,f,b),Y(I,"i_iif"),c=null)}window.interstitialAdFrame=c;e=window;e.google_llp||(e.google_llp={});e=e.google_llp;f=e[9];if(!f){const {promise:g, 
resolve:h}=new pb;f={promise:g,resolve:h};e[9]=f}e=f;e.resolve(c)});if(0===D(b,5,0)||2===D(b,5,0)||E(b,16)){const c=document.getElementById("ad_iframe");null!=c.contentDocument?Da(c.contentDocument,a):document.getElementById("ad_iframe").addEventListener("load",a)}else a()})(Gb);}).call(this);
