# Generated by Django 2.2.7 on 2022-02-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoofingAttack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='email',
            field=models.CharField(help_text='jjj', max_length=200),
        ),
    ]
